%This is an example how read data from *.fig matlab files

clear all;
close all;

mfn = mfilename;
version = 'ver# 2015.08.03';
disp(char(['-> ' mfn ' ' version]));


html = 0;
sep_leg = 1; % The goal:  make a chart with each legend aside (so not to obstruct the graph).

%load reaction
alpha = 0.01; % Significance level


%(mean_evi3.mat is mean_evi3.fig, that generated by matlab)
%load this file
figure_1 = load (char(['mean_' char(output_state) '_evi3.mat'])); %generated by main.m
figure2 = figure_1.hgS_070000; 
% we parse mean_evi3.fig for getting xdata and ydata
% internal format of  mean_evi3.fig
ydata = figure2.children(1,1).children(1,1).properties.YData; % mean_EVI3
xdata = figure2.children(1,1).children(1,1).properties.XData; % DOY

if (size(xdata,2)<=22)
    disp(['Data is not enough: size: ', num2str(size(xdata,2)), ', min: ', num2str(min(xdata)), ' and max: ', num2str(max(xdata)),' of DOY']);
    return;
end

ydata = velue_correction(ydata);

disp(char(['<- ' mfn ' ' version]));
